# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\xiaohaozi\Desktop\xxx\xiaohaozi_bak.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cx_Oracle
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cxButton = QtWidgets.QPushButton(self.centralwidget)
        self.cxButton.setObjectName("cxButton")
        self.horizontalLayout.addWidget(self.cxButton)
        self.plcxButton = QtWidgets.QPushButton(self.centralwidget)
        self.plcxButton.setObjectName("plcxButton")
        self.horizontalLayout.addWidget(self.plcxButton)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 22))
        self.menubar.setObjectName("menubar")
        self.cx_menu = QtWidgets.QMenu(self.menubar)
        self.cx_menu.setObjectName("cx_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.cx_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cxButton.setText(_translate("MainWindow", "一键查询"))
        self.plcxButton.setText(_translate("MainWindow", "批量查询"))
        self.lineEdit.setText(_translate("MainWindow", "输入数量"))
        self.pushButton.setText(_translate("MainWindow", "设置"))
        self.cx_menu.setTitle(_translate("MainWindow", "简单查询"))
        self.load_data()
    
    def load_data(self):
        try:
            connection = cx_Oracle.connect(connect_str)
            cursor = connection.cursor()
            cursor.execute(query)

            rows = cursor.fetchall()
            columns = [desc[0] for desc in cursor.description]
            self.table.setColumnCount(len(columns))
            self.table.setHorizontalHeaderLabels(columns)
            self.table.setRowCount(len(rows))

            for row_idx, row_data in enumerate(rows):
                for col_idx, col_data in enumerate(row_data):
                    item = QTableWidgetItem(str(col_data))
                    self.table.setItem(row_idx, col_idx, item)

            cursor.close()
            connection.close()
        except cx_Oracle.DatabaseError as e:
            print(f'数据库连接失败，报错：{e}')
